-- JS Gráfica SITE V2 — v2A
-- Migration 001: camada pública + modalidades + assets + read-model/RPC.
-- NÃO altera colunas existentes de public.jsgrafica_produtos.
-- Aplicar somente na conta Supabase correta da JS Gráfica e primeiro em ambiente de preview/staging.

begin;

-- PRELIGHT BLOQUEANTE
DO $$
DECLARE
  id_type text;
BEGIN
  IF to_regclass('public.jsgrafica_produtos') IS NULL THEN
    RAISE EXCEPTION 'PRECHECK FAIL: public.jsgrafica_produtos não existe';
  END IF;

  SELECT format_type(a.atttypid, a.atttypmod)
    INTO id_type
  FROM pg_attribute a
  WHERE a.attrelid = 'public.jsgrafica_produtos'::regclass
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF id_type IS NULL THEN
    RAISE EXCEPTION 'PRECHECK FAIL: public.jsgrafica_produtos.id não foi encontrado';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    WHERE a.attrelid = 'public.jsgrafica_produtos'::regclass
      AND a.attname = 'ativo' AND a.attnum > 0 AND NOT a.attisdropped
  ) THEN
    RAISE EXCEPTION 'PRECHECK FAIL: public.jsgrafica_produtos.ativo não foi encontrado';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    WHERE a.attrelid = 'public.jsgrafica_produtos'::regclass
      AND a.attname = 'nome' AND a.attnum > 0 AND NOT a.attisdropped
  ) THEN
    RAISE EXCEPTION 'PRECHECK FAIL: public.jsgrafica_produtos.nome não foi encontrado';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    WHERE a.attrelid = 'public.jsgrafica_produtos'::regclass
      AND a.attname = 'categoria' AND a.attnum > 0 AND NOT a.attisdropped
  ) THEN
    RAISE EXCEPTION 'PRECHECK FAIL: public.jsgrafica_produtos.categoria não foi encontrado';
  END IF;

  IF to_regclass('public.jsgrafica_catalogo_publicacao') IS NULL THEN
    EXECUTE format($sql$
      CREATE TABLE public.jsgrafica_catalogo_publicacao (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        produto_id %s NOT NULL UNIQUE REFERENCES public.jsgrafica_produtos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
        sku text NOT NULL UNIQUE,
        slug text NOT NULL UNIQUE,
        familia text,
        colecao_tema text,
        versao text NOT NULL,
        status_produto text NOT NULL DEFAULT 'SELECIONADO',
        status_produto_fonte text NOT NULL DEFAULT 'PRODUTOS',
        status_produto_atualizado_em timestamptz NOT NULL DEFAULT now(),
        status_produto_referencia text,
        status_publicacao text NOT NULL DEFAULT 'RASCUNHO',
        destaque boolean NOT NULL DEFAULT false,
        resumo_curto text NOT NULL,
        descricao_publica text NOT NULL,
        publico text,
        problema_resolvido text,
        ocasioes jsonb NOT NULL DEFAULT '[]'::jsonb,
        diferenciais jsonb NOT NULL DEFAULT '[]'::jsonb,
        narrativa_comercial text,
        especificacao_digital jsonb NOT NULL DEFAULT '{}'::jsonb,
        especificacao_fisica jsonb NOT NULL DEFAULT '{}'::jsonb,
        entrega jsonb NOT NULL DEFAULT '{}'::jsonb,
        licenca_direitos jsonb NOT NULL DEFAULT '{}'::jsonb,
        upsells jsonb NOT NULL DEFAULT '[]'::jsonb,
        cross_sells jsonb NOT NULL DEFAULT '[]'::jsonb,
        tags text[] NOT NULL DEFAULT ARRAY[]::text[],
        relacionados text[] NOT NULL DEFAULT ARRAY[]::text[],
        seo_title text NOT NULL,
        seo_description text NOT NULL,
        versao_aprovada text,
        teste_fisico_ok boolean,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT jsgrafica_catalogo_publicacao_status_publicacao_chk CHECK (status_publicacao IN ('RASCUNHO','PUBLICADO','OCULTO')),
        CONSTRAINT jsgrafica_catalogo_publicacao_status_produto_chk CHECK (status_produto IN ('IDEIA','PESQUISA','SELECIONADO','EM_PRODUCAO','EM_TESTE','ATIVO','PAUSADO','DESCONTINUADO')),
        CONSTRAINT jsgrafica_catalogo_publicacao_status_produto_fonte_chk CHECK (status_produto_fonte = 'PRODUTOS'),
        CONSTRAINT jsgrafica_catalogo_publicacao_slug_chk CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
      )
    $sql$, id_type);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.jsgrafica_catalogo_modalidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacao_id bigint NOT NULL REFERENCES public.jsgrafica_catalogo_publicacao(id) ON DELETE CASCADE,
  tipo text NOT NULL,
  ativo boolean NOT NULL DEFAULT false,
  conteudo_incluido jsonb NOT NULL DEFAULT '[]'::jsonb,
  preco numeric(12,2),
  modo_preco text NOT NULL,
  prazo text NOT NULL,
  dados_cliente jsonb NOT NULL DEFAULT '{}'::jsonb,
  regras_personalizacao jsonb NOT NULL DEFAULT '{}'::jsonb,
  orcamento_obrigatorio boolean NOT NULL DEFAULT false,
  whatsapp_mensagem text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jsgrafica_catalogo_modalidades_tipo_chk CHECK (tipo IN ('DIGITAL','PERSONALIZADO','IMPRESSO','PERSONALIZADO_IMPRESSO','IMPRESSO_ENVIO')),
  CONSTRAINT jsgrafica_catalogo_modalidades_modo_preco_chk CHECK (modo_preco IN ('FIXO','A_PARTIR_DE','SOB_CONSULTA')),
  CONSTRAINT jsgrafica_catalogo_modalidades_preco_chk CHECK (
    (modo_preco IN ('FIXO','A_PARTIR_DE') AND preco IS NOT NULL AND preco >= 0)
    OR (modo_preco = 'SOB_CONSULTA' AND (preco IS NULL OR preco >= 0))
  ),
  UNIQUE (publicacao_id, tipo)
);

CREATE TABLE IF NOT EXISTS public.jsgrafica_catalogo_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacao_id bigint NOT NULL REFERENCES public.jsgrafica_catalogo_publicacao(id) ON DELETE CASCADE,
  tipo text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'catalogo-publico',
  storage_path text NOT NULL,
  alt_text text NOT NULL,
  ordem integer NOT NULL DEFAULT 0,
  versao text NOT NULL,
  aprovado boolean NOT NULL DEFAULT false,
  publicavel boolean NOT NULL DEFAULT false,
  largura integer,
  altura integer,
  mime_type text,
  bytes bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jsgrafica_catalogo_assets_tipo_chk CHECK (tipo IN ('CAPA','MOCKUP','GALERIA')),
  CONSTRAINT jsgrafica_catalogo_assets_dimensao_chk CHECK ((largura IS NULL OR largura > 0) AND (altura IS NULL OR altura > 0)),
  CONSTRAINT jsgrafica_catalogo_assets_path_chk CHECK (storage_path !~ '(^|/)(\.\.|\.)($|/)'),
  UNIQUE (storage_bucket, storage_path)
);

CREATE INDEX IF NOT EXISTS jsgrafica_catalogo_publicacao_status_idx ON public.jsgrafica_catalogo_publicacao(status_publicacao, status_produto);
CREATE INDEX IF NOT EXISTS jsgrafica_catalogo_publicacao_destaque_idx ON public.jsgrafica_catalogo_publicacao(destaque) WHERE destaque;
CREATE INDEX IF NOT EXISTS jsgrafica_catalogo_modalidades_publicacao_idx ON public.jsgrafica_catalogo_modalidades(publicacao_id, ativo);
CREATE INDEX IF NOT EXISTS jsgrafica_catalogo_assets_publicacao_idx ON public.jsgrafica_catalogo_assets(publicacao_id, aprovado, publicavel, ordem);

-- RLS: tabelas novas não são lidas/escritas diretamente pelo site.
ALTER TABLE public.jsgrafica_catalogo_publicacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jsgrafica_catalogo_modalidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jsgrafica_catalogo_assets ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.jsgrafica_catalogo_publicacao FROM anon, authenticated;
REVOKE ALL ON TABLE public.jsgrafica_catalogo_modalidades FROM anon, authenticated;
REVOKE ALL ON TABLE public.jsgrafica_catalogo_assets FROM anon, authenticated;

-- Restringe somente as sequences NOVAS. Não toca sequences do PDV existente.
DO $$
DECLARE seqname text;
BEGIN
  FOR seqname IN
    SELECT pg_get_serial_sequence('public.jsgrafica_catalogo_publicacao','id')
    UNION ALL SELECT pg_get_serial_sequence('public.jsgrafica_catalogo_modalidades','id')
    UNION ALL SELECT pg_get_serial_sequence('public.jsgrafica_catalogo_assets','id')
  LOOP
    IF seqname IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM anon, authenticated', seqname);
    END IF;
  END LOOP;
END $$;

-- updated_at genérico para as tabelas novas
CREATE OR REPLACE FUNCTION public.jsgrafica_catalogo_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_catalogo_publicacao_touch ON public.jsgrafica_catalogo_publicacao;
CREATE TRIGGER trg_catalogo_publicacao_touch BEFORE UPDATE ON public.jsgrafica_catalogo_publicacao FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_touch_updated_at();
DROP TRIGGER IF EXISTS trg_catalogo_modalidades_touch ON public.jsgrafica_catalogo_modalidades;
CREATE TRIGGER trg_catalogo_modalidades_touch BEFORE UPDATE ON public.jsgrafica_catalogo_modalidades FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_touch_updated_at();
DROP TRIGGER IF EXISTS trg_catalogo_assets_touch ON public.jsgrafica_catalogo_assets;
CREATE TRIGGER trg_catalogo_assets_touch BEFORE UPDATE ON public.jsgrafica_catalogo_assets FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_touch_updated_at();

-- Publicação exige contrato mínimo + gates + ao menos uma modalidade e um asset aprovados.
CREATE OR REPLACE FUNCTION public.jsgrafica_catalogo_validar_publicacao()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE op_ativo boolean;
BEGIN
  IF NEW.status_publicacao = 'PUBLICADO' THEN
    IF NEW.status_produto <> 'ATIVO' THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: status_produto deve ser ATIVO';
    END IF;
    IF nullif(trim(NEW.status_produto_referencia),'') IS NULL THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: status_produto_referencia deve apontar para o handoff/decisão de PRODUTOS';
    END IF;
    IF nullif(trim(NEW.sku),'') IS NULL OR nullif(trim(NEW.slug),'') IS NULL OR nullif(trim(NEW.versao),'') IS NULL
       OR nullif(trim(NEW.resumo_curto),'') IS NULL OR nullif(trim(NEW.descricao_publica),'') IS NULL
       OR nullif(trim(NEW.seo_title),'') IS NULL OR nullif(trim(NEW.seo_description),'') IS NULL THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: campos públicos obrigatórios ausentes';
    END IF;

    SELECT ativo INTO op_ativo FROM public.jsgrafica_produtos WHERE id = NEW.produto_id;
    IF op_ativo IS DISTINCT FROM true THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: produto operacional não está ativo';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.jsgrafica_catalogo_modalidades m WHERE m.publicacao_id = NEW.id AND m.ativo = true) THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: nenhuma modalidade ativa';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.jsgrafica_catalogo_assets a WHERE a.publicacao_id = NEW.id AND a.aprovado = true AND a.publicavel = true) THEN
      RAISE EXCEPTION 'PUBLICAÇÃO BLOQUEADA: nenhum asset aprovado/publicável';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_catalogo_validar_publicacao ON public.jsgrafica_catalogo_publicacao;
CREATE TRIGGER trg_catalogo_validar_publicacao
BEFORE INSERT OR UPDATE OF status_publicacao, status_produto, status_produto_referencia, produto_id, sku, slug, versao, resumo_curto, descricao_publica, seo_title, seo_description
ON public.jsgrafica_catalogo_publicacao
FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_validar_publicacao();

-- Impede remover o último gate filho de uma publicação já PUBLICADA.
CREATE OR REPLACE FUNCTION public.jsgrafica_catalogo_validar_integridade_filhos()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE pub_id bigint;
DECLARE pub_status text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    pub_id := OLD.publicacao_id;
  ELSE
    pub_id := NEW.publicacao_id;
  END IF;
  SELECT status_publicacao INTO pub_status FROM public.jsgrafica_catalogo_publicacao WHERE id = pub_id;
  IF pub_status = 'PUBLICADO' THEN
    IF TG_TABLE_NAME = 'jsgrafica_catalogo_modalidades' AND NOT EXISTS (
      SELECT 1 FROM public.jsgrafica_catalogo_modalidades WHERE publicacao_id = pub_id AND ativo = true
    ) THEN
      RAISE EXCEPTION 'ALTERAÇÃO BLOQUEADA: publicação ficaria sem modalidade ativa';
    END IF;
    IF TG_TABLE_NAME = 'jsgrafica_catalogo_assets' AND NOT EXISTS (
      SELECT 1 FROM public.jsgrafica_catalogo_assets WHERE publicacao_id = pub_id AND aprovado = true AND publicavel = true
    ) THEN
      RAISE EXCEPTION 'ALTERAÇÃO BLOQUEADA: publicação ficaria sem asset aprovado/publicável';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_catalogo_modalidades_integridade ON public.jsgrafica_catalogo_modalidades;
CREATE CONSTRAINT TRIGGER trg_catalogo_modalidades_integridade AFTER INSERT OR UPDATE OR DELETE ON public.jsgrafica_catalogo_modalidades DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_validar_integridade_filhos();
DROP TRIGGER IF EXISTS trg_catalogo_assets_integridade ON public.jsgrafica_catalogo_assets;
CREATE CONSTRAINT TRIGGER trg_catalogo_assets_integridade AFTER INSERT OR UPDATE OR DELETE ON public.jsgrafica_catalogo_assets DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION public.jsgrafica_catalogo_validar_integridade_filhos();

-- Read-model privado: não é schema exposto ao PostgREST.
CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC;
REVOKE ALL ON SCHEMA private FROM anon, authenticated;

CREATE OR REPLACE VIEW private.jsgrafica_catalogo_publico AS
SELECT
  p.id AS produto_id,
  pub.sku,
  pub.slug,
  p.nome,
  p.categoria,
  pub.familia,
  pub.colecao_tema,
  pub.versao,
  pub.resumo_curto,
  pub.descricao_publica,
  pub.publico,
  pub.problema_resolvido,
  pub.ocasioes,
  pub.diferenciais,
  pub.narrativa_comercial,
  pub.especificacao_digital,
  pub.especificacao_fisica,
  pub.entrega,
  pub.licenca_direitos,
  pub.tags,
  pub.destaque,
  pub.seo_title,
  pub.seo_description,
  COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', m.id,
      'tipo', m.tipo,
      'ativo', m.ativo,
      'conteudo_incluido', m.conteudo_incluido,
      'preco', m.preco,
      'modo_preco', m.modo_preco,
      'prazo', m.prazo,
      'dados_cliente', m.dados_cliente,
      'regras_personalizacao', m.regras_personalizacao,
      'orcamento_obrigatorio', m.orcamento_obrigatorio,
      'whatsapp_mensagem', m.whatsapp_mensagem
    ) ORDER BY m.id)
    FROM public.jsgrafica_catalogo_modalidades m
    WHERE m.publicacao_id = pub.id AND m.ativo = true
  ), '[]'::jsonb) AS modalidades,
  COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', a.id,
      'tipo', a.tipo,
      'storage_bucket', a.storage_bucket,
      'storage_path', a.storage_path,
      'public_url', concat(current_setting('app.settings.supabase_url', true), '/storage/v1/object/public/', a.storage_bucket, '/', a.storage_path),
      'alt_text', a.alt_text,
      'ordem', a.ordem,
      'largura', a.largura,
      'altura', a.altura
    ) ORDER BY a.ordem, a.id)
    FROM public.jsgrafica_catalogo_assets a
    WHERE a.publicacao_id = pub.id AND a.aprovado = true AND a.publicavel = true
  ), '[]'::jsonb) AS assets
FROM public.jsgrafica_produtos p
JOIN public.jsgrafica_catalogo_publicacao pub ON pub.produto_id = p.id
WHERE p.ativo = true
  AND pub.status_produto = 'ATIVO'
  AND pub.status_publicacao = 'PUBLICADO'
  AND EXISTS (SELECT 1 FROM public.jsgrafica_catalogo_modalidades m WHERE m.publicacao_id = pub.id AND m.ativo = true)
  AND EXISTS (SELECT 1 FROM public.jsgrafica_catalogo_assets a WHERE a.publicacao_id = pub.id AND a.aprovado = true AND a.publicavel = true);

-- RPCs estritamente de leitura. O SITE chama apenas estas funções com publishable/anon key.
CREATE OR REPLACE FUNCTION public.jsgrafica_catalogo_listar(
  p_categoria text DEFAULT NULL,
  p_modalidade text DEFAULT NULL,
  p_destaque boolean DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, private
AS $$
  SELECT COALESCE(jsonb_agg(to_jsonb(v) ORDER BY v.destaque DESC, v.nome), '[]'::jsonb)
  FROM private.jsgrafica_catalogo_publico v
  WHERE (p_categoria IS NULL OR v.categoria = p_categoria)
    AND (p_destaque IS NULL OR v.destaque = p_destaque)
    AND (p_modalidade IS NULL OR EXISTS (
      SELECT 1 FROM jsonb_array_elements(v.modalidades) m WHERE m->>'tipo' = p_modalidade
    ));
$$;

CREATE OR REPLACE FUNCTION public.jsgrafica_catalogo_por_slug(p_slug text)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, private
AS $$
  SELECT to_jsonb(v) FROM private.jsgrafica_catalogo_publico v WHERE v.slug = p_slug LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.jsgrafica_catalogo_listar(text,text,boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.jsgrafica_catalogo_por_slug(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.jsgrafica_catalogo_listar(text,text,boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.jsgrafica_catalogo_por_slug(text) TO anon, authenticated;

-- O executor deve definir app.settings.supabase_url no banco ANTES de validar URLs de assets:
-- ALTER DATABASE postgres SET app.settings.supabase_url = 'https://PROJECT.supabase.co';
-- Não é secret, mas depende da conta correta e por isso fica no runbook, não hardcoded aqui.

commit;
